version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend # Ensure this points to the correct backend directory
      dockerfile: Dockerfile # This line is optional if the file is named 'Dockerfile'
    ports:
      - "4001:4001"
    environment:
      MONGODB_URI: mongodb://mongo:27017/mern-cafe-employee
      TEST_MONGODB_URI: mongodb://mongo:27017/testing
      PORT: 4001
    depends_on:
      - mongo

volumes:
  mongo_data:
